### ISSUE TITLE
How to create if you already have bedrock knowledge and osss in aws

### ISSUE THREAD

**Issue by chowdhury-bc** [aws-samples/serverless-rag-demo#112]
can you please provide code for the UI only so we can plug the existing knowledgebase and osss

**Comment by Fraser27** [comment]
Option 1:
The UI is available [here](https://github.com/aws-samples/serverless-rag-demo/tree/main/artifacts/chat-ui), you can deploy it on your local machine and then look to integrate it with your existing KBase and OSS.

Option 2:
You can integrate your KBase with our Lambda function instead. You can go through this README.md [section](https://github.com/aws-samples/serverless-rag-demo/tree/main/artifacts/chat-ui) and see how to integrate it with our stack

**Comment by chowdhury-bc** [comment]
Hello @Fraser27  i was trying to follow your link but its failing on config.json not there. Do you have example config.json so i can pugin in value?

Option 2 going to same link like option 1

can you please point where in UI its communicating with api gateway and lambda
