### ISSUE TITLE
Add feature to use hugging face llms

### ISSUE THREAD

**Issue by Dicondur** [aws-samples/serverless-rag-demo#117]

**Comment by Fraser27** [comment]
@Dicondur : We currently rely on Amazon Bedrock for access to LLMs, before bedrock we accessed LLMs on Sagemaker hosted on GPU's. This project intends to run on serverless AWS- managed resources. However you could fork it and customize to suit your requirements. You could pull in an HF model host it on an EC2 GPU in AWS and access it via a lambda function. The Lambda would have to be in the same VPC as the EC2.
