### ISSUE TITLE
Support for Bedrock service and make sagemaker endpoint as optional

### ISSUE THREAD

**Issue by amitkml** [aws-samples/serverless-rag-demo#38]
It looks like the sagemaker endpoint creation is mandatory and that is quite costly. So why not make that optional and use bedrock service model for model endpoint.

**Comment by Fraser27** [comment]
You have an option to use Anthrhopic Claude models with Bedrock. When deploying this stack, if you choose Amazon Bedrock(option 1) , no Sagemaker endpoints are created. It's only if you select Llama2 /Falcon ,those would then be deployed on a Sagemaker endpoint .
