### ISSUE TITLE
Unknown service : bedrock-runtime

### ISSUE THREAD

**Issue by vamsee9201** [aws-samples/serverless-rag-demo#69]
Hello,
This is a great project. This was really helpful. I was able to create run this locally. But, creating the docker container is giving me a unknown service error : it is not able to find bedrock-runtime. It would be great if you can help me with this.

**Comment by Fraser27** [comment]
@vamsee9201 We dont use dockerized lambdas to invoke/query any LLM on Amazon Bedrock . 
Could you provide the steps your trying ? 

Follow the steps in the Readme to provision the infrastructure via Amazon Cloudshell.
