### ISSUE TITLE
Updating the code (question not issue...)

### ISSUE THREAD

**Issue by mdcox** [aws-samples/serverless-rag-demo#70]
Hello,

I am working with this awesome project and I have everything working from the base image, great work I love it!

I am however wondering if the only current way to update the html page is to make the updates and then re-run `creator.sh`. I don't see any other mentions of updating the scripts and I am new-ish to code build so I am not sure if there is a better route to take?

I have tried this route and in codebuild, it says the build was successful but I do not see any html changes, now this could be due to errors in the deployment so I have been checking those. 

Thank you for any support!

**Comment by Fraser27** [comment]
Hi @mdcox , 
          The html is rendered through a Lambda function (llm-html-generator-dev). Search for **llm-html-generator-*** lambda function in your AWS region of deployment.
Explore the function's code directory, under the content folder you'll find the HTML page([rag_bedrock.html](https://github.com/aws-samples/serverless-rag-demo/blob/main/artifacts/html_lambda/content/rag_bedrock.html)) that you could easily edit without having to redeploy the entire stack.
Hope this helps

**Comment by mdcox** [comment]
Ahh yes that makes so much sense haha thank you very much!
